packages:
- '.'
extra-deps:
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- stb-image-0.2.1
- unicode-properties-3.2.0.0
- language-ecmascript-0.19.1.0
- ekg-core-0.1.1.7
- aeson-diff-1.1.0.12
- lens-aeson-1.2
- github: lamdu/bindings-freetype-gl
  commit: 440ee6a7a5f25ebc24e087d0d3ea9f588da6bb93
- github: lamdu/lamdu-calculus
  commit: 6fe1f9d89d584eb173c10f851a819865824fb5ee
- github: lamdu/momentu
  commit: 24f97dfab74ef8aa5d13acdb065b9b758d87bc2c
- github: lamdu/hypertypes
  commit: c7f6b2f0caa633a5c4a0eb4a7d1f0026307c00c4
- github: lamdu/graphics-drawingcombinators
  commit: 39500dd189b0676468848d1f452ac31c7f0ec461
- github: lamdu/freetype2
  commit: 046328d92312d65638440132c016a3081d9c32a4
- github: lamdu/FreetypeGL
  commit: 18ca298d8fd48ad18f75264553b57714bf070c77
- github: tweag/inline-js
  commit: 5da3690abd454e5e94021dcd4486484e89fc419f
  subdirs:
    - inline-js-core

resolver: lts-19.1

allow-newer: true

ghc-options:
  # this is for weeder:
  "$locals": -fwrite-ide-info

# require-stack-version: ">=2.5"
