packages:
- '.'
extra-deps:
- bitmap-0.0.2
- bitmap-opengl-0.0.1.5
- stb-image-0.2.1
- unicode-properties-3.2.0.0
- language-ecmascript-0.19.1.0
- ekg-core-0.1.1.7
- aeson-diff-1.1.0.12
- lens-aeson-1.2
- github: lamdu/rocksdb-haskell
  commit: b0016acefbb38b1fbe148163f226f4cae15c03c7
- github: lamdu/bindings-freetype-gl
  commit: 440ee6a7a5f25ebc24e087d0d3ea9f588da6bb93
- github: lamdu/lamdu-calculus
  commit: 6fe1f9d89d584eb173c10f851a819865824fb5ee
- github: lamdu/momentu
  commit: 6edd1bbc59812a4389dd98a34ae8cd27ee529b44
- github: lamdu/hypertypes
  commit: 9a28e3863b0e2525f38ce7b6efabbc056d3145b2
- github: lamdu/graphics-drawingcombinators
  commit: 39500dd189b0676468848d1f452ac31c7f0ec461
- github: lamdu/freetype2
  commit: 046328d92312d65638440132c016a3081d9c32a4
- github: lamdu/FreetypeGL
  commit: 18ca298d8fd48ad18f75264553b57714bf070c77
- github: tweag/inline-js
  commit: 8512b09d2c0533a41d5d2aef182b11a58c420c10
  subdirs:
    - inline-js-core

resolver: lts-19.1

allow-newer: true

ghc-options:
  # this is for weeder:
  "$locals": -fwrite-ide-info

# require-stack-version: ">=2.5"
